config/routes.rb
Rails.application.routes.draw do

  root 'calls#new'
  get 'pokemon', to: 'pokemons#index'

  resources :teams
  resources :mentors
  resources :messages
  resources :logs
  get 'attend', to: 'mentors#attend'
  post 'attend', to: 'mentors#attend_update'
  get 'call', to: 'calls#new'
  post 'call', to: 'calls#create'
  # Ajax系処理
  post 'new_message_ajax', to: 'messages#ajax_create'
  get 'get_mentor_src_ajax', to: 'mentors#ajax_get_src'

  get 'index', to: 'pokemons#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]
  def new
    @mentors = Mentor.select(:id, :name, :subscription).where(attend: true)
    @logs = Log.joins(:team, :message).eager_load(:mentor).order("logs.created_at DESC")
  end

  def create
    @call = call_params
    @log = Log.new
    @log[:team_id] = @call[:team][:id]
    @log[:mentor_id] = @call[:mentor][:id]
    @log[:level] = @call[:level][:value]
    @log[:message_id] = @call[:message][:id]

    # テキストで入力されていたらそっちで更新
    msg = @call[:message][:subscription].strip_with_full_size_space
    if !msg.blank?
      if Message.exists?(:subscription => msg)
        @log[:message_id] = Message.find_by(:subscription => msg).id
      else
        # 登録されていないメッセージなので新規作成
        new_msg = Message.create(subscription: msg)
        @log[:message_id] = new_msg[:id]
      end
    end
    @log.save
    slack_message = make_slack_message(@log)
    Slack.chat_postMessage(text: slack_message, username: ENV['SLACK_USERNAME'], channel: ENV['SLACK_CHANNEL'])

		# プッシュ通知用のJSON生成
		@mentors = Mentor.select(:id, :name).where(attend: true)

		if !@log.mentor.nil?
      @mentor_id = @log.mentor.id
		else
			@mentor_id = ''
    end

    # お困りごとの画像ソースの変数を定義
    if File.exist?("#{Rails.root}/public/images/pokemon/enemy/#{@log.message.id.to_s}.png")
      src_enemy = "enemy/#{@log.message.id.to_s}.png"
    else
      src_enemy = "enemy/unknown.png"
    end

    # メンターの画像ソースの変数を定義
    if File.exist?("#{Rails.root}/public/images/pokemon/mentor/#{@mentor_id.to_s}.png")
      src_mentor = "mentor/#{@mentor_id.to_s}.png"
    else
      src_mentor = "mentor/trainer.png"
    end


		data = {
      log_id: @log.id,
			team_name: @log.team.name,
      src_mentor: src_mentor,
      src_enemy: src_enemy,
			subscription: @log.message.subscription,
			level: @log.level.to_s,
			mentor_id: @mentor_id,
			mentors: @mentors
		 }
	 	# サーバからpokemon画面にプッシュ通知
		WebsocketRails[:call].trigger "pokemon", data

    redirect_to root_path, notice: 'メッセージが送信されました'
  end

  private
    def call_params
      params.require(:call).permit(
      team: [:id],
      message: [:id, :subscription],
      level: [:value],
      mentor: [:id]
      )
    end
end

#stringクラス拡張
class String
  def strip_with_full_size_space!
    s = "　\s\v"
    sub!(/^[#{s}]*([^#{s}]+)[#{s}]*$/o, '\1')
  end
  def strip_with_full_size_space
    clone.strip_with_full_size_space!
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/new.html.erb
<!-- form -->
<div id="call-form" class="col-md-9">
<div class="panel panel-default">
  <div class="panel-heading">メンター呼び出し</div>
  <div class="panel-body">
    <%= form_tag call_path, method: :post do %>
      <fieldset class="form-group">
        <label for="call[team]">チーム名</label>
        <%= collection_select "call[team]", :id, Team.all, :id, :name, {}, {:class => 'form-control'} %>
      </fieldset>

      <fieldset class="form-group">
        <label for="call[team]">お困りごと</label>
        <%= collection_select "call[message]", :id, Message.all, :id, :subscription, {}, {:class => 'form-control'} %>
        <small class="text-muted">お困りごとがない場合は..</small>
        <div id="new-message">
          <label for="call[message]">お困りごとを新規登録</label>
          <%= text_field "call[message]", :subscription, :maxlength => 256, :size => 32,  :class => 'form-control' %>
          <a class="btn btn-default" role="button" onClick="createNewMessage()">登録</a>
        </div>
      </fieldset>

      <fieldset class="form-group">
        <label for="call[level]"><%= "ふんいき" %></label>
        <p id="level-item">
        <input id="level-slider"type="text" name="call[level][value]" data-provide="slider" data-slider-ticks="[1,2,3]" data-slider-ticks-labels='["ちょっときて", "やばいかも", "緊急事態発生"]' data-slider-min="1" data-slider-max="3" data-slider-step="1" data-slider-value="2" data-slider-tooltip="hide">
        </p>
      </fieldset>

      <fieldset class="form-group">
        <label for="call[mentor]"><%= "メンターの指定" %></label>
        <input type="hidden" name="call[mentor][id]" class="form-control" value="">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a id="collapse-btn" data-toggle="collapse" data-target="#mentor-list">メンターを指定する</a>
          </div>
          <div id="mentor-list" class="panel-collapse collapse">
            <ul id="mentors" class="row row-eq-height">
              <% @mentors.each do |m| %>
                <li class="col-sm-6 col-md-4 col-lg-3" data-mentor-id="<%= m.id %>">
                  <div class="thumbnail">

										<% if File.exist? "#{Rails.root}/public/images/mentor/#{m.id.to_s}.png" %>
                      <p class="mentor-image"><%= image_tag "/images/mentor/#{m.id.to_s}.png" %></p>
                    <% else %>
                      <p class="mentor-image"><%= image_tag "/images/mentor/mentor_default.png" %></p>
                    <% end %>
                    <p class="mentor-name"><%= m.name %></p>
                    <p class="mentor-description"><%= !m.subscription.blank? ? m.subscription : "" %></p>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </fieldset>

      <%= submit_tag "送信", :class => 'btn btn-success btn-block btn-lg' %>
    <% end %>
  </div>
</div>
</div>
<!-- //form -->
<!-- logs -->
<div class="col-md-3">
  <%= render 'layouts/log' %>
</div>
<!-- //logs -->