config/routes.rb
Rails.application.routes.draw do

  root 'calls#new'
  get 'pokemon', to: 'pokemons#index'

  resources :teams
  resources :mentors
  resources :messages
  resources :logs
  get 'attend', to: 'mentors#attend'
  post 'attend', to: 'mentors#attend_update'
  get 'call', to: 'calls#new'
  post 'call', to: 'calls#create'
  # Ajax系処理
  post 'new_message_ajax', to: 'messages#ajax_create'
  get 'get_mentor_src_ajax', to: 'mentors#ajax_get_src'

  get 'index', to: 'pokemons#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :mentor
  belongs_to :message
  belongs_to :team

  validates :team_id, presence: true
  validates :message_id, presence: true
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  has_many :logs

  validates :name, presence: true, uniqueness: true
  validates :attend, inclusion: {in: [true, false]}
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :logs

  validates :subscription, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :logs

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
  validates :password, presence: true
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]
  def new
    @mentors = Mentor.select(:id, :name, :subscription).where(attend: true)
    @logs = Log.joins(:team, :message).eager_load(:mentor).order("logs.created_at DESC")
  end

  def create
    @call = call_params
    @log = Log.new
    @log[:team_id] = @call[:team][:id]
    @log[:mentor_id] = @call[:mentor][:id]
    @log[:level] = @call[:level][:value]
    @log[:message_id] = @call[:message][:id]

    # テキストで入力されていたらそっちで更新
    msg = @call[:message][:subscription].strip_with_full_size_space
    if !msg.blank?
      if Message.exists?(:subscription => msg)
        @log[:message_id] = Message.find_by(:subscription => msg).id
      else
        # 登録されていないメッセージなので新規作成
        new_msg = Message.create(subscription: msg)
        @log[:message_id] = new_msg[:id]
      end
    end
    @log.save
    slack_message = make_slack_message(@log)
    Slack.chat_postMessage(text: slack_message, username: ENV['SLACK_USERNAME'], channel: ENV['SLACK_CHANNEL'])

		# プッシュ通知用のJSON生成
		@mentors = Mentor.select(:id, :name).where(attend: true)

		if !@log.mentor.nil?
      @mentor_id = @log.mentor.id
		else
			@mentor_id = ''
    end

    # お困りごとの画像ソースの変数を定義
    if File.exist?("#{Rails.root}/public/images/pokemon/enemy/#{@log.message.id.to_s}.png")
      src_enemy = "enemy/#{@log.message.id.to_s}.png"
    else
      src_enemy = "enemy/unknown.png"
    end

    # メンターの画像ソースの変数を定義
    if File.exist?("#{Rails.root}/public/images/pokemon/mentor/#{@mentor_id.to_s}.png")
      src_mentor = "mentor/#{@mentor_id.to_s}.png"
    else
      src_mentor = "mentor/trainer.png"
    end


		data = {
      log_id: @log.id,
			team_name: @log.team.name,
      src_mentor: src_mentor,
      src_enemy: src_enemy,
			subscription: @log.message.subscription,
			level: @log.level.to_s,
			mentor_id: @mentor_id,
			mentors: @mentors
		 }
	 	# サーバからpokemon画面にプッシュ通知
		WebsocketRails[:call].trigger "pokemon", data

    redirect_to root_path, notice: 'メッセージが送信されました'
  end

  private
    def call_params
      params.require(:call).permit(
      team: [:id],
      message: [:id, :subscription],
      level: [:value],
      mentor: [:id]
      )
    end
end

#stringクラス拡張
class String
  def strip_with_full_size_space!
    s = "　\s\v"
    sub!(/^[#{s}]*([^#{s}]+)[#{s}]*$/o, '\1')
  end
  def strip_with_full_size_space
    clone.strip_with_full_size_space!
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  def index
    @logs = Log.joins(:team, :message).eager_load(:mentor).order("logs.created_at DESC")
  end

  # Ajax処理
  def update
    puts :text => params
    @log = Log.find(params[:id])
    if @log.update(mentor_id: params[:mentor_id])
      status = 'success'
    else
      status = 'fail'
    end
    render json: {status: status, data: @log}
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  def index
    @mentors = Mentor.all
  end

  def new
    @mentor = Mentor.new
  end

  def create
    @mentor = Mentor.new(mentor_params)
    @mentor[:attend] = false
    if @mentor.save
      redirect_to mentors_path
    else
      render 'new'
    end
  end

  def edit
    @mentor = Mentor.find(params[:id])
  end

  def update
    @mentor = Mentor.find(params[:id])
    if @mentor.update(update_mentor_params)
      redirect_to mentors_path
    else
      render edit_mentor_path(@mentor)
    end
  end

  def attend
    @mentors = Mentor.all
  end

  def attend_update
    @mentor_attends = attend_params
    @mentor_attends.each do |mentor|
      update_mentor = Mentor.find(mentor[1][:id])
      update_mentor.update(attend: mentor[1][:attend])
    end
    redirect_to attend_path
  end

  # Ajax処理
  def ajax_get_src
    # メンターの画像ソースの変数を定義
    if File.exist?("#{Rails.root}/public/images/pokemon/mentor/#{params[:mentor_id].to_s}.png")
      src_mentor = "mentor/#{params[:mentor_id].to_s}.png"
    else
      src_mentor = "mentor/trainer.png"
    end
    render json: {src_mentor: src_mentor}
  end

  private

  def mentor_params
    params.require(:mentor).permit(:name, :subscription)
  end

  def update_mentor_params
    params.require(:mentor).permit(:id, :name, :subscription)
  end

  def attend_params
    params.require(:mentor)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :logged_in?, only: [:ajax_create]
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update(update_message_params)
      redirect_to messages_path
    else
      render edit_message_path(@message)
    end
  end

  # Ajax処理
  def ajax_create
    @message = Message.new(subscription: params[:subscription].strip_with_full_size_space)
    if @message.save
      status = 'success'
    else
      status = 'fail'
    end
      render json: {status: status, data: @message}
  end

  private

  def message_params
    params.require(:message).permit(:subscription)
  end

  def update_message_params
    params.require(:message).permit(:id, :subscription)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController	< ApplicationController
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to mentors_path, notice: 'Logged in.'
    else
      redirect_to root_path, alert: 'You are not mentor. Thank you.'
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to teams_path
    else
      render 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(update_team_params)
      redirect_to teams_path
    else
      render edit_team_path(@team)
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end

  def update_team_params
    params.require(:team).permit(:id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user.nil?
      redirect_to login_path, alert: 'Please Login.'
    end
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <small>This is the system for calling mentors @ enPiT2016, University of Tsukuba.</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <h1>
      <img src="/images/i_logo.png" alt="logo">
    </h1>
  </div>
</header>

app/views/layouts/_log.html.erb
<div class="panel panel-default">
  <div class="panel-heading">呼び出し履歴</div>
  <div class="panel-body">
    <!-- filter -->
    <div id="filter">
      <p>
        <label for="call[team]">チーム名: </label>
        <%= collection_select "call[team]", :id, Team.all, :id, :name, {:include_blank => "すべて"}, {:class => 'form-control', :onchange => 'filterLogs()'} %>
      </p>
      <p>
        <label for="call[team]">お困りごと: </label>
        <%= collection_select "call[message]", :id, Message.all, :id, :subscription, {:include_blank => "あらゆるお困りごと"}, {:class => 'form-control', :onchange => 'filterLogs()'} %>
      </p>
    </div>
    <!-- //filter -->
    <ul id="log-list">
      <% @logs.each do |l| %>
        <li class="thumbnail match" data-team="<%= l.team[:id] %>" data-message="<%= l.message[:id] %>" style="display:none">
          <p class="log-info">
            <%= l.team[:name]%> のまえに
            <% if l[:level] == 1 %>温厚そうな
            <% elsif l[:level] == 2 %>ふつうの
            <% elsif l[:level] == 3 %>激昂した
            <% end %>
            <%= l.message[:subscription]%> が あらわれた！
          </p>
          <% if !l.mentor.nil? %>
            <p class="mentor-info">
              <%= l.mentor[:name]%> がかけつけた
            </p>
          <% end %>
          <p class="log-date text-right">
            <%= l[:created_at].strftime("%Y/%m/%d %H:%M") %>
          </p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_mentor_side_menu.html.erb
<!-- PC用メニュー -->
<div id="pc-menu" class="col-sm-3 hidden-xs">
  <div class="panel panel-default">
    <div class="panel-heading">メニュー</div>
    <ul class="nav nav-stacked">
      <li class="nav-sub-heading">メンター設定</li>
      <li><%= link_to "一覧表示", mentors_path %></li>
      <li><%= link_to "出席登録", attend_path %></li>
      <li><%= link_to "新規登録", new_mentor_path %></li>
      <li class="nav-sub-heading">メッセージ(お困りごと)設定</li>
      <li><%= link_to "一覧表示", messages_path %></li>
      <li><%= link_to "新規登録", new_message_path %></li>
      <li class="nav-sub-heading">チーム設定</li>
      <li><%= link_to "一覧表示", teams_path %></li>
      <li><%= link_to "新規登録", new_team_path %></li>
      <li class="nav-sub-heading">ログ(呼び出し履歴)表示</li>
      <li><%= link_to "一覧表示", logs_path %></li>
    </ul>
  </div>
</div>
<!-- スマートフォン用メニュー -->
<div id="sp-menu" class="col-sm-3 visible-xs">
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading"><a data-toggle="collapse" href="#sp-nav">メニュー</a></div>
    <div id="sp-nav" class="panel-collapse collapse">
      <ul class="nav nav-stacked">
        <li class="nav-sub-heading">メンター設定</li>
        <li><%= link_to "一覧表示", mentors_path %></li>
        <li><%= link_to "出席登録", attend_path %></li>
        <li><%= link_to "新規登録", new_mentor_path %></li>
        <li class="nav-sub-heading">メッセージ(お困りごと)設定</li>
        <li><%= link_to "一覧表示", messages_path %></li>
        <li><%= link_to "新規登録", new_message_path %></li>
        <li class="nav-sub-heading">チーム設定</li>
        <li><%= link_to "一覧表示", teams_path %></li>
        <li><%= link_to "新規登録", new_team_path %></li>
        <li class="nav-sub-heading">ログ(呼び出し履歴)表示</li>
        <li><%= link_to "一覧表示", logs_path %></li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/layouts/_message.html.erb
<div id="message">
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, class: "alert alert-#{key}") do %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= value %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>enPiTGo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://code.createjs.com/easeljs-0.8.2.min.js"></script>
  <script src="https://code.createjs.com/tweenjs-0.6.2.min.js"></script>
  <script src="https://code.createjs.com/soundjs-0.6.2.min.js"></script>
	<%= javascript_include_tag controller.controller_name, 'data-turbolinks-track' => true %>
  <!-- <script src="assets<%= asset_path controller.controller_name %>.js"></script> -->
	<!-- <%= asset_path controller.controller_name, type: :javascript %> -->
  <%= csrf_meta_tags %>
  <%= favicon_link_tag() %>
  <meta name="viewport" content="width=device-width">
</head>
<body id="<%= controller.controller_name %>">
<!-- header -->
<%= render 'layouts/header' %>
<!-- //header -->
<!-- message -->
<%= render 'layouts/message' %>
<!-- //message-->
<!-- contents -->
<div id="contents">
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</div>
<!-- //contents -->
<!-- footer -->
<%= render 'layouts/footer' %>
<!-- //footer -->
</body>
</html>

app/views/shared/_mentor_form.html.erb
<%= form_for @mentor do |f| %>
  <div class="form-group">
    <%= f.label "氏名" %>
    <%= f.text_field :name, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label "使用可能スキル/紹介文" %>
    <%= f.text_area :subscription, {cols: 32, rows: 3, class: 'form-control'}  %>
  </div>
  <%= f.submit "登録", :class => 'btn btn-primary btn-block' %>
<% end %>

app/views/shared/_message_form.html.erb
<%= form_for @message do |f| %>
  <div class="form-group">
    <%= f.label "お困りごと内容" %>
    <%= f.text_field :subscription, size: 32, class:'form-control' %>
  </div>
  <%= f.submit "登録", :class => 'btn btn-primary btn-block' %>
<% end %>

app/views/shared/_team_form.html.erb
<%= form_for @team do |f| %>
  <div class="form-group">
    <%= f.label "チーム名" %>
    <%= f.text_field :name, size: 32, class: 'form-control' %>
  </div>
  <%= f.submit "登録", :class => 'btn btn-primary btn-block' %>
<% end %>